insert into listings
(title, description, salary, tags, company, address, city, state, phone, email, requirements, benefits, user_id)
values(
    'Web Developer',
    'Join our team as a Web Developer and create amazing web applications',
    '85000',
    'web development, programming',
    'WebTech Solutions',
    '789 Web Ave',
    'Chicago',
    'IL',
    '456-876-5432',
    'info@webtechsolutions.com',
    'Bachelors degree in Computer Science or related field, proficiency in HTML, CSS, JavaScript',
    'Competitive salary, professional development opportunities, friendly work environment',
    3
), (
    'Data Analyst',
    'We are hiring a Data Analyst to analyze and interpret data for insights',
    '75000',
    'data analysis, statistics',
    'Data Insights LLC',
    '123 Data Ave',
    'New York',
    'NY',
    '123-456-7890',
    'info@datainsights.com',
    'Proficiency in SQL, Python, or R, and experience with data visualization tools',
    'Competitive salary, professional development opportunities, friendly work environment',
    3),
    (
    'Graphic Designer',
    'Join our creative team as a Graphic Designer and bring ideas to life',
    '70000',
    'graphic design, creative',
    'CreativeWorks Inc.',
    '234 Design Blvd',
    'Albany',
    'NY',
    '499-321-9876',
    'info@creativeworks.com',
    'Bachelors degree in Graphic Design or related field, proficiency in Adobe Creative Suite',
    'Flexible work hours, creative work environment, opportunities for growth',
    2),
    (
    'Marketing Specialist',
    'We are looking for a Marketing Specialist to create and manage marketing campaigns',
    '70000',
    'marketing, advertising',
    'Marketing Pros',
    '456 Market St',
    'San Francisco',
    'CA',
    '454-344-3344',
    'info@marketingpros.com',
    'Bachelors degree in Marketing or related field, experience in digital marketing',
    'Competitive salary, professional development opportunities, friendly work environment',
    2),
    (
    'Software Engineer',
    'We are seeking a skilled software engineer to develop high-quality software solutions',
    '90000',
    'development, coding, java, python',
    'CodeWorks Inc.',
    '789 Code St',
    'San Diego',
    'CA',
    '555-456-7890',
    'info@codeworks.com',
    'Proficiency in Java, Python, or other relevant programming languages',
    'Flexible work hours, professional development opportunities, friendly work environment',
    3),
    (
    'Data Scientist',
    'We are looking for a Data Scientist to analyze complex data and generate insights',
    '100000',
    'data science, machine learning',
    'DataGenius Corp',
    '567 Data Drive',
    'Boston',
    'MA',
    '684-789-1234',
    'info@datagenius.com',
    'Masters or Ph.D. in Data Science or related field, experience with machine learning algorithms',
    'Competitive salary, remote work options, professional development',
    1);